apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgASrGgIcWHnqVCy8OSjxteOmprZB9ijBi6iYGY+bVgpVPXnF/V12xKVXN+QJvcrcjDZCRq7mseCSieajn1lozrWQrLBoHKxUUBcuYg0IfbhDqVCJcU7A4II4Zgv+tFVXmA3nt//EDfjKli0Zdqcdv2D9R7M1Sq9DQWD6EQxmLuXHFYGC4u6Rt+NAgs98+TIC9TBTUDUG7M7cx1Fnc/sMAFY/dv3U1Tzmispr5QmJsoUc0RKxIF7u9QjCp2UO+n/g/s6l2WKouUEDgdVCqTBZpQ3DY19jxwNI0NxC58WZo40yf2BP9Zz9k6rctFir5ztotpcxJPfOEtcdHQITtGOtYkS78/M/VEI92qCIg5DQl8/4jTVTCLDjzMYpnYMomxE3mYipBs/anCP3Q6MDyfRFgOR1BV+ibSvmlzykHqYdL3xhTVqwdcACs78Ei2rXmawf9L5lro/4nAhZAo0KYrTr/BZdjOpRSKVLFN1t/vfUHlKyHMHTC6Cq0JG1AuuLjj28q+HyJxQxLsdNNGZxSVp/HHB31Qu+9c0ryAflxNGfamr9gtfH9uNQRI0uztrl5MPm2oup+hN5kgP4BLxk8xntQvSBbCsGJh+HwQalBMLGfQqmKa71Fjt1MzR6m03UWvqlx9lhiGjFKCqHH8T5IHDQjo0Ltu6au7NFPEabvT6XVEyrJd5uftzv9GLDSz+RoRxAkuF04cOnnyKzPjN8J16IFkqjR9dX9h64uN62nlDJ/TVnFsG/8BxogA4fCmHLTMb0CFMQknVQ3Lh8P0/3xZX1c3tUjhz3cWJGOgBMwOQUtPLrQlSL/z9U+OPkFZp/Af01l8QhUBf/7MeaDR6juhNn7LPq6W17WL160jg+Fsgnp8ZgNE61dueQeo+4pdfPUorqlZQmlT9UIE1Wm6SGpztANsHhtSlL/pm
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

