---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
  annotations:
    recipients.argocd-notifications.argoproj.io: "slack:jenkins"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: production
  source:
    directory:
      exclude: jsonnetfile.*
      jsonnet:
        libs:
          - kube-prometheus/vendor
    path: kube-prometheus
    repoURL: https://github.com/ansel1/argo-combined-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---