apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCXVmCvzkVRlD9CsEGQGpUrOzox+/fdTI41RJhah9H4DLUV4KJ+HP58R3VzYzsVT472c36ZwsbVDwY0lx3b/R8x2LxYkNmAhKYu/y4m9gm/OjG7tBGe2mi9kxS/GRfiNXpolHy3sSU0C4ZNh1AzroY920o2J33O6CTvXygdz5BEOjcT7yvbGNkwPBmpHg0LQiNU7hqAFN2p+cSUOCjlV+R9aSUh69rRrOhb/Y340qxRvX6nA1SsbbAGFN0QtLwGBIblEG/eR4eSVmswcQEfo1vLoVDDWN8Cz6dAEO5AJawrpSWkbeljV2wZhCSltW7rRJyyEwSeMaIG4UZpgHcllVmrdmtD5vUkTMYNo5tE4GuoFugeGOraWfaILjLcUrQpp3IkzCGuiC0ezaTBUMz828bD852+4mVtDRsNWJrnIUGeToKfPQc7yNtaL0EvtWSogLhBeAHPfmaMlNtUzOUh5Y33V+w6+rrSdb/gUuRs7Fn2K1zeSxvRuS69qnpbm+eGDFu2p7XFLwFEznd8dZ3WIq1Pt5KCIGv+Kb6/9EtXvWr/dfq87uHoEeZLPYad27h6f8aSJ5Ys0PfkYBWMmS+qrUWM92aIFUyA6Lnt0uMgQuugoSgtE200cNzGI8Z5r6+kUQUavQDQIwIiMloVTxhH7pM2TAJsIDj6GsEFLf3as6+PnqhveavGtvJn++7NEhlDv4t/xfCHR+Wb92In0wFxmRau6rzbXZ61wJWdEVD3g4p+9EvaLseBZYNA
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

