apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAblZJGn3Hm8sdwEdOC0gXXBf1JJHw8GJXnb3PcjFvsA7m8PhF+tZrOa7yEgTpWAMrlXHhdy3ApCPqJDvWfncW8tzxyHoG8h5cpDRMVo7ayzOikwb6R4yb+p3mKJBCZbel5Z7q65gBRnrEw2sDJlX4telmGopwxZyvQU2paI98XouXuHVJvOX8wSV8OfIQKYKaWKpfoCLPg31gtgpUeb34QqDrrG7YH7rJQhXp+3rFXD9ZyjJD1jHopsX8IXfsgbPJyFgSwndVYxBYeLrd5hh3AIh92yKvVSAsq2g+GrIqaGrR7sscoSpKFOIF4l9WNfIdE60JtFE55kXJATAOdXxphqs/S1gjTJuxKf16KW1OHl/FA1UsEqARpL+80y+kRx1oTNJND8tihOH/YnYgfU5b5rfpkvQqjFBeD9z8Y+4Jdks+LWAVj+E1mSUw2qG2SdrUtGYtY32vE7HMsiWg+TJQPPh6Gstu/VxNRwVSn3ZK783qn5zt/FPJdTUJSqReqP9uMzDC5O4vDoQ9U5+sxkZRCKEJtajXqmpr6SdNQn7hkeTKcDNBsXeAANSFDe/KfsbBiSWDfXpeHGOQ3s0AosZBzSGzo80FL7touE/VZLqG8jAc2WZ2FNZLAQm3KsX6KEC1olnK5DGir7nZMeT8dvpg5+4vjB5aNdO13m0y+Utk/+DfcZvo6l7Bz0L9NoBn6VwH4drnZzU2qUFL+F8oetoiam9rXDFNPVVZ6PMIsoUdpxvUDbAbFPJCk
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

