apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- event-sources.yaml
- sensors.yaml
- githubcred.yaml
patches:
  - path: event-bus-patch.yaml
namespace: argo-events

